version: '3'
services:
  redis:
    image: 'redis'
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/docker-flask-app/src
  postgres_db:
    container_name: postgres
    image: postgres:10
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD} 
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/db_create.sql:/docker-entrypoint-initdb.d/init.sql
         